version: "3.7"
services:
  rust:
    container_name: rust
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - cockroachdb_1
      - cockroachdb_2
      - cockroachdb_3
      - yb-master
      - yb-tserver
      - yb-tserver2
    command: cargo watch -x "run" -w src
    networks:
      - roachnet
    environment:
      # DATABASE_URL: "postgresql://root@roach1:26257/bench?sslmode=disable"
      # DATABASE_URL: "postgresql://root@postgres:5432/bench"
      DATABASE_URL: "postgresql://yugabyte:yugabyte@yb-tserver-n1:5433/bench"
  postgres:
    image: postgres:11.1
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - roachnet
    volumes:
      - "./tmp/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ""
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_DB: bench
    restart: always
    command: ["-c", "max_connections=200"]
  cockroachdb_1:
    image: cockroachdb/cockroach:v19.2.4
    container_name: roach1
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - roachnet
    restart: always
    command:
      - start
      - "--insecure"
      - "--join=roach1,roach2,roach3"
    volumes:
      - "./tmp/cockroach-data/roach1:/cockroach/cockroach-data"
  cockroachdb_2:
    image: cockroachdb/cockroach:v19.2.4
    container_name: roach2
    networks:
      - roachnet
    restart: always
    command:
      - start
      - "--insecure"
      - "--join=roach1,roach2,roach3"
    volumes:
      - "./tmp/cockroach-data/roach2:/cockroach/cockroach-data"
  cockroachdb_3:
    image: cockroachdb/cockroach:v19.2.4
    container_name: roach3
    networks:
      - roachnet
    restart: always
    command:
      - start
      - "--insecure"
      - "--join=roach1,roach2,roach3"
    volumes:
      - "./tmp/cockroach-data/roach3:/cockroach/cockroach-data"
  yb-master:
      image: yugabytedb/yugabyte:2.1.2.0-b10
      container_name: yb-master-n1
      networks:
      - roachnet
      volumes:
      - ./tmp/yb/master:/mnt/master
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master-n1:7100",
                "--rpc_bind_addresses=yb-master-n1:7100",
                "--replication_factor=2"]
      ports:
      - "7000:7000"
      environment:
        SERVICE_7000_NAME: yb-master
  yb-tserver:
      image: yugabytedb/yugabyte:2.1.2.0-b10
      container_name: yb-tserver-n1
      networks:
      - roachnet
      volumes:
      - ./tmp/yb/tserver-n1:/mnt/tserver
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver-n1:9100",
                "--tserver_master_addrs=yb-master-n1:7100"
                ]
      ports:
      - "9042:9042"
      - "6379:6379"
      - "5433:5433"
      - "9000:9000"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
      depends_on:
      - yb-master
  yb-tserver2:
      image: yugabytedb/yugabyte:2.1.2.0-b10
      container_name: yb-tserver2-n1
      networks:
      - roachnet
      volumes:
      - ./tmp/yb/tserver2-n1:/mnt/tserver
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--tserver_master_addrs=yb-master-n1:7100"
                ]
      depends_on:
      - yb-master
  yb-tserver3:
      image: yugabytedb/yugabyte:2.1.2.0-b10
      container_name: yb-tserver3-n1
      networks:
      - roachnet
      volumes:
      - ./tmp/yb/tserver3-n1:/mnt/tserver
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--tserver_master_addrs=yb-master-n1:7100"
                ]
      depends_on:
      - yb-master
networks:
  roachnet:
